- name: Enabling mod_rewrite for apache (Debian)
  apache2_module: state=present name=rewrite
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  
- name: Checking that webserver is running (Debian)
  service: name=apache2 state=started
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  
- name: Checking that webserver is running (RHEL)
  service: name=httpd state=started
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'