- name: Checking that nginx is running
  service: name=nginx state=started

- name: Installing php5-fpm
  apt: name=php5-fpm
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  
- set_fact: zray_nginx_conf_parameter="nginx=/etc/nginx/conf.d"
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  
- set_fact: zray_nginx_conf_parameter="nginx=/etc/nginx/default.d"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'